[package]
name = "redstone-itf"
version = "0.1.0"
description = "Interface to Redstone Oracle"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "redstone_itf"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
test-bpf = []
debug = []

[dependencies]
anchor-lang = "0.28.0"
